#!/usr/bin/env bash
# Temp file, copy of 3

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
newlines="\\\n\tlocation /redirect_me {\n\t\trewrite ^/redirect_me https://www.youtube.com/watch?v=LQPftxAXJsU;\n\t\t}"
sudo sed -i "72i $newlines" /etc/nginx/sites-available/default
