#!/usr/bin/env bash
# Configure ufw so that it blocks all incoming traffic, except the TCP ports 22, 80, 443
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
sudo ufw enable
